In [44]:
import numpy as np
import pandas as pd

In [45]:
df = pd.read_csv('data/train.csv')
df.head()

,ID,Year,Games_Won,Games_Lost,Games_Drawn,Points_For,Points_Against,Percentage,Ladder_Position,Finals,...,Teams_Prev,Ladder_Position_Next,Teams_Next,Close_Games_Won,Close_Games_Lost,Away_Games_Won,Last_Five,Average_Attendance,Players_Used,Victorian
0,250,199x,12,10,0,2250,2071,108.64,8,Finalist,...,16.0,1,16,5,6,5,2,53944.0,38,True
1,1035,195x,12,6,0,1485,1205,123.24,3,Finalist,...,12.0,12,12,3,3,6,2,26001.0,35,True
2,605,189x,11,3,0,704,383,183.81,1,Runner-up,...,NaN,4,8,3,2,5,4,4000.0,34,True
3,694,193x,3,15,0,1367,1932,70.76,12,NaN,...,12.0,10,12,0,2,1,0,12557.0,38,False
4,1131,191x,13,1,0,970,678,143.07,1,Premier,...,6.0,2,9,6,1,6,5,37689.0,29,False

In [46]:
# Change all 'Year' columns to decades
df['Year'] = df['Year'].apply(lambda x: str(x)[:3] + '0')
df.head()

,ID,Year,Games_Won,Games_Lost,Games_Drawn,Points_For,Points_Against,Percentage,Ladder_Position,Finals,...,Teams_Prev,Ladder_Position_Next,Teams_Next,Close_Games_Won,Close_Games_Lost,Away_Games_Won,Last_Five,Average_Attendance,Players_Used,Victorian
0,250,1990,12,10,0,2250,2071,108.64,8,Finalist,...,16.0,1,16,5,6,5,2,53944.0,38,True
1,1035,1950,12,6,0,1485,1205,123.24,3,Finalist,...,12.0,12,12,3,3,6,2,26001.0,35,True
2,605,1890,11,3,0,704,383,183.81,1,Runner-up,...,NaN,4,8,3,2,5,4,4000.0,34,True
3,694,1930,3,15,0,1367,1932,70.76,12,NaN,...,12.0,10,12,0,2,1,0,12557.0,38,False
4,1131,1910,13,1,0,970,678,143.07,1,Premier,...,6.0,2,9,6,1,6,5,37689.0,29,False

In [47]:
# Add values to empty 'Finals' rows
df['Finals'] = df['Finals'].fillna("N/A")
df.head()

,ID,Year,Games_Won,Games_Lost,Games_Drawn,Points_For,Points_Against,Percentage,Ladder_Position,Finals,...,Teams_Prev,Ladder_Position_Next,Teams_Next,Close_Games_Won,Close_Games_Lost,Away_Games_Won,Last_Five,Average_Attendance,Players_Used,Victorian
0,250,1990,12,10,0,2250,2071,108.64,8,Finalist,...,16.0,1,16,5,6,5,2,53944.0,38,True
1,1035,1950,12,6,0,1485,1205,123.24,3,Finalist,...,12.0,12,12,3,3,6,2,26001.0,35,True
2,605,1890,11,3,0,704,383,183.81,1,Runner-up,...,NaN,4,8,3,2,5,4,4000.0,34,True
3,694,1930,3,15,0,1367,1932,70.76,12,N/A,...,12.0,10,12,0,2,1,0,12557.0,38,False
4,1131,1910,13,1,0,970,678,143.07,1,Premier,...,6.0,2,9,6,1,6,5,37689.0,29,False

In [48]:
# Change decimals in 'Ladder_Position_Prev' and 'Teams_Prev' to integers
print(df['Ladder_Position_Prev'])
print(df['Teams_Prev'])

0       14.0
1        5.0
2        NaN
3       12.0
4        3.0
        ...
1098     2.0
1099     8.0
1100     8.0
1101     4.0
1102     7.0
Name: Ladder_Position_Prev, Length: 1103, dtype: float64
0       16.0
1       12.0
2        NaN
3       12.0
4        6.0
        ...
1098     9.0
1099     8.0
1100    12.0
1101    18.0
1102    12.0
Name: Teams_Prev, Length: 1103, dtype: float64

In [51]:
# Convert 'Ladder_Position_Prev' and 'Teams_Prev' to integers and handle NaN values
df['Ladder_Position_Prev'] = df['Ladder_Position_Prev'].apply(lambda x: int(x) if pd.notna(x) else 0)
df['Teams_Prev'] = df['Teams_Prev'].apply(lambda x: int(x) if pd.notna(x) else 0)

print(df['Ladder_Position_Prev'])
print(df['Teams_Prev'])

0       14
1        5
2        0
3       12
4        3
        ..
1098     2
1099     8
1100     8
1101     4
1102     7
Name: Ladder_Position_Prev, Length: 1103, dtype: int64
0       16
1       12
2        0
3       12
4        6
        ..
1098     9
1099     8
1100    12
1101    18
1102    12
Name: Teams_Prev, Length: 1103, dtype: int64

In [54]:
df['Ladder_Position'].head(30)

0      8
1      3
2      1
3     12
4      1
5      5
6     14
7      2
8      8
9     11
10     5
11     6
12     6
13     7
14     2
15     4
16     5
17    16
18    12
19     7
20    17
21     6
22     9
23    12
24     3
25     3
26     5
27     7
28     5
29     6
Name: Ladder_Position, dtype: int64